name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        GCP_JSON_BASE64: ${{secrets.GCP_JSON_BASE64}}
        MDP_BDD: ${{secrets.MDP_BDD}}
        OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
    steps:
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gdpesme/pfe-esme-notebot:latest
